coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto

github_checks:
  annotations: false

flags:
  integration:
    paths:
      - ".*"
    carryforward: true

comment:
  layout: "diff, files"
