coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto

github_checks:
  annotations: false

comment:
    layout: "files"
    hide_project_coverage: TRUE
