coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto

comment:
    layout: "condensed_header, files, condensed_footer"
    hide_project_coverage: TRUE
